# Generated by Django 2.1 on 2018-08-06 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ulid2


class Migration(migrations.Migration):

    dependencies = [("safka", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=ulid2.generate_ulid_as_uuid,
                        primary_key=True,
                        serialize=False,
                        editable=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=ulid2.generate_ulid_as_uuid,
                        primary_key=True,
                        serialize=False,
                        editable=False,
                    ),
                ),
                ("ctime", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                (
                    "mtime",
                    models.DateTimeField(auto_now=True, verbose_name="last modification time"),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True)),
                ("frozen_goods", models.TextField(blank=True)),
                ("fresh_goods", models.TextField(blank=True)),
                ("halal_goods", models.TextField(blank=True)),
                ("genres", models.ManyToManyField(to="safka.Genre")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="LocationProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=ulid2.generate_ulid_as_uuid,
                        primary_key=True,
                        serialize=False,
                        editable=False,
                    ),
                ),
                ("ctime", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                (
                    "mtime",
                    models.DateTimeField(auto_now=True, verbose_name="last modification time"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="safka.Location"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=ulid2.generate_ulid_as_uuid,
                        primary_key=True,
                        serialize=False,
                        editable=False,
                    ),
                ),
                ("ctime", models.DateTimeField(auto_now_add=True, verbose_name="creation time")),
                (
                    "mtime",
                    models.DateTimeField(auto_now=True, verbose_name="last modification time"),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(blank=True, max_length=100)),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="locationproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="safka.Product"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="products",
            field=models.ManyToManyField(through="safka.LocationProduct", to="safka.Product"),
        ),
        migrations.AlterUniqueTogether(
            name='locationproduct',
            unique_together={('product', 'location')},
        ),
    ]
